/**
 * Shell completion generators for bash, zsh, and fish.
 */

import {
  listTopLevelCommands,
  NESTED_SUBCOMMANDS,
  getInstallInstructions,
} from "./cli-reference.js";

export const COMPLETIONS_SCHEMA = "todos.cli_completions.v1";

const GLOBAL_FLAGS = ["--json", "-j", "--help", "-h", "--version", "-V"];

export function generateBashCompletion(): string {
  const cmds = listTopLevelCommands().join(" ");
  const nested = Object.entries(NESTED_SUBCOMMANDS)
    .map(([cmd, subs]) => `      ${cmd}) opts="${subs.join(" ")}" ;;`)
    .join("\n");

  return `# todos bash completion (${COMPLETIONS_SCHEMA})
# Generated by: todos completion bash

_todos_completions() {
  local cur prev words cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  local top_level="${cmds}"
  local global_flags="${GLOBAL_FLAGS.join(" ")}"

  case "\${prev}" in
${nested}
    completion)
      opts="bash zsh fish install"
      ;;
    *)
      opts="\${top_level} \${global_flags}"
      ;;
  esac

  if [[ \${cur} == -* ]]; then
    COMPREPLY=( $(compgen -W "\${global_flags}" -- \${cur}) )
  else
    COMPREPLY=( $(compgen -W "\${opts}" -- \${cur}) )
  fi
}

complete -F _todos_completions todos
`;
}

export function generateZshCompletion(): string {
  const cmds = listTopLevelCommands();
  const nestedCases = Object.entries(NESTED_SUBCOMMANDS)
    .map(([cmd, subs]) => `    ${cmd}) _arguments "${subs.map((s) => `'${s}[${s}]'`).join(" ")}" ;;`)
    .join("\n");

  return `#compdef todos
# todos zsh completion (${COMPLETIONS_SCHEMA})

_todos() {
  local -a commands
  commands=(
${cmds.map((c) => `    '${c}:${c} command'`).join("\n")}
  )

  _arguments \\
    '--json[JSON output]' \\
    '-j[JSON output]' \\
    '--help[Show help]' \\
    '-h[Show help]' \\
    '1: :->command' \\
    '*::arg:->args'

  case $state in
    command)
      _describe 'todos command' commands
      ;;
    args)
      case $words[1] in
${nestedCases}
        completion)
          _arguments '1: :(bash zsh fish install)'
          ;;
      esac
      ;;
  esac
}

_todos "$@"
`;
}

export function generateFishCompletion(): string {
  const lines: string[] = [
    `# todos fish completion (${COMPLETIONS_SCHEMA})`,
    "complete -c todos -f",
    ...GLOBAL_FLAGS.map((f) => `complete -c todos -s ${f.replace(/^--?/, "")} -l ${f.replace(/^-/, "")}`),
  ];

  for (const cmd of listTopLevelCommands()) {
    lines.push(`complete -c todos -n "__fish_use_subcommand" -a "${cmd}" -d "${cmd} command"`);
  }

  for (const [parent, subs] of Object.entries(NESTED_SUBCOMMANDS)) {
    for (const sub of subs) {
      lines.push(
        `complete -c todos -n "__fish_seen_subcommand_from ${parent}" -a "${sub}" -d "${sub}"`,
      );
    }
  }

  lines.push('complete -c todos -n "__fish_seen_subcommand_from completion" -a "bash zsh fish install"');

  return lines.join("\n") + "\n";
}

export function generateCompletionInstallScript(shell: "bash" | "zsh" | "fish"): string {
  const instructions = getInstallInstructions(shell);
  const body = shell === "bash" ? generateBashCompletion()
    : shell === "zsh" ? generateZshCompletion()
    : generateFishCompletion();

  return [
    "#!/usr/bin/env bash",
    `# Install ${shell} completions for todos`,
    ...instructions.map((l) => (l.startsWith("#") ? l : `# ${l}`)),
    "",
    body,
  ].join("\n");
}
