// Dependency-light command paths used only to validate exact `<command> --help`
// metadata invocations before the full Commander graph is imported.
export const TODOS_CLI_HELP_COMMAND_PATHS = new Set([
  "active",
  "add",
  "agent",
  "agent-runs",
  "agent-runs adapter-remove",
  "agent-runs adapter-set",
  "agent-runs adapters",
  "agent-runs cancel",
  "agent-runs list",
  "agent-runs queue",
  "agent-runs retry",
  "agent-runs run-next",
  "agent-update",
  "agents",
  "agents-normalize",
  "agents-update",
  "api-key",
  "api-keys",
  "api-keys create",
  "api-keys generate",
  "api-keys list",
  "api-keys revoke",
  "api-keys verify",
  "approvals",
  "approvals approve",
  "approvals check",
  "approvals expire",
  "approvals list",
  "approvals reject",
  "approvals require",
  "approve",
  "assign",
  "audit-ledger",
  "audit-ledger list",
  "audit-ledger seal",
  "audit-ledger show",
  "audit-ledger verify",
  "backup",
  "backup create",
  "backup integrity",
  "backup restore",
  "backup verify",
  "blame",
  "blocked",
  "board",
  "board create",
  "board delete",
  "board export",
  "board import",
  "board list",
  "board move",
  "board show",
  "board tui",
  "branch-plan",
  "bridge-import",
  "bulk",
  "burndown",
  "calendar",
  "calendar add",
  "calendar export",
  "calendar import",
  "calendar list",
  "capacity",
  "capacity forecast",
  "capacity list",
  "capacity remove",
  "capacity set",
  "claim",
  "comment",
  "completion",
  "completions",
  "config",
  "context",
  "context-pack",
  "contracts",
  "contracts check",
  "contracts request-review",
  "contracts review",
  "contracts set",
  "contracts show",
  "count",
  "dashboard",
  "dedupe",
  "dedupe merge",
  "dedupe scan",
  "delete",
  "demo-fixtures",
  "deps",
  "dispatch",
  "dispatch run",
  "dispatches",
  "doctor",
  "doctor routing",
  "done",
  "encryption",
  "encryption list",
  "encryption remove",
  "encryption set",
  "encryption status",
  "encryption test",
  "env-snapshot",
  "env-snapshot capture",
  "env-snapshot compare",
  "environment-snapshot",
  "event-hooks",
  "event-hooks list",
  "event-hooks remove",
  "event-hooks set",
  "event-hooks test",
  "events",
  "events emit",
  "events list",
  "events replay",
  "export",
  "extensions",
  "extensions compat",
  "extensions discover",
  "extensions inspect",
  "extensions install",
  "extensions list",
  "extensions remove",
  "extensions verify",
  "extract",
  "extract-watch",
  "fail",
  "fields",
  "fields query",
  "fields set",
  "fields show",
  "find-commit",
  "find-ref",
  "findings",
  "findings list",
  "findings resolve-missing",
  "findings upsert",
  "focus",
  "handoff",
  "health",
  "heartbeat",
  "history",
  "hook",
  "hook install",
  "hook uninstall",
  "hooks",
  "hooks install",
  "import",
  "import-md",
  "inbox",
  "inbox add",
  "inbox git",
  "inbox list",
  "inbox parse",
  "inbox show",
  "init",
  "inspect",
  "interactive",
  "issues",
  "issues import",
  "issues report",
  "knowledge",
  "knowledge add",
  "knowledge export",
  "knowledge list",
  "knowledge search",
  "knowledge show",
  "knowledge snapshot",
  "link-commit",
  "link-ref",
  "list",
  "lists",
  "local-snapshots",
  "lock",
  "log",
  "log-progress",
  "machines",
  "machines archive",
  "machines delete",
  "machines heartbeat",
  "machines register",
  "machines set-primary",
  "machines status",
  "machines sync",
  "machines tasks",
  "machines topology",
  "machines unarchive",
  "manual",
  "markdown-import",
  "mcp",
  "mine",
  "next",
  "normalize-agents",
  "notifications",
  "notifications check",
  "onboarding",
  "org",
  "overdue",
  "pin",
  "plans",
  "policies",
  "policies explain",
  "policies list",
  "policies remove",
  "policies set",
  "policies validate",
  "priorities",
  "project-bootstrap",
  "project-panel",
  "project-rename",
  "projects",
  "projects-path",
  "projects-path list",
  "projects-path remove",
  "projects-path set",
  "ready",
  "recap",
  "record-verification",
  "redaction",
  "redaction add",
  "redaction scan",
  "redaction status",
  "redistribute",
  "references",
  "references resolve",
  "refs",
  "release",
  "release-compat",
  "release-compat check",
  "release-notes",
  "reliability",
  "reliability export",
  "reliability list",
  "reliability show",
  "remove",
  "report",
  "report-failure",
  "reports",
  "reports local",
  "retention",
  "retention cleanup",
  "retro",
  "retrospectives",
  "retrospectives create",
  "retrospectives export",
  "retrospectives list",
  "retrospectives show",
  "review-queue",
  "reviews",
  "reviews approve",
  "reviews claim",
  "reviews list",
  "reviews reopen",
  "reviews request",
  "reviews return",
  "reviews rules",
  "reviews rules list",
  "reviews rules remove",
  "reviews rules set",
  "risks",
  "risks add",
  "risks close",
  "risks export",
  "risks list",
  "risks score",
  "risks show",
  "risks update",
  "roadmap",
  "roadmaps",
  "roadmaps create",
  "roadmaps delete",
  "roadmaps export",
  "roadmaps import",
  "roadmaps list",
  "roadmaps milestones",
  "roadmaps milestones add",
  "roadmaps milestones update",
  "roadmaps releases",
  "roadmaps releases set",
  "roadmaps show",
  "roadmaps update",
  "runs",
  "runs artifact",
  "runs artifact-verify",
  "runs begin",
  "runs command",
  "runs event",
  "runs file",
  "runs finish",
  "runs list",
  "runs show",
  "runs simulate",
  "runs start",
  "sandbox",
  "sandbox check",
  "sandbox explain",
  "sandbox list",
  "sandbox remove",
  "sandbox set",
  "scale",
  "scale compact",
  "scale report",
  "scorecards",
  "sdk-fixtures",
  "search",
  "self-update",
  "serve",
  "show",
  "sla",
  "snapshots",
  "sprint",
  "stale",
  "standup",
  "start",
  "status",
  "steal",
  "storage",
  "storage artifacts",
  "storage artifacts download",
  "storage artifacts upload",
  "storage shadow-drain",
  "storage shadow-status",
  "storage status",
  "storage sync-plan",
  "stream",
  "summary",
  "sync",
  "tag",
  "task",
  "task route-state",
  "task upsert",
  "task workflow-pointers",
  "task-lists",
  "template-export",
  "template-history",
  "template-import",
  "template-init",
  "template-library",
  "template-preview",
  "templates",
  "templates-export",
  "templates-history",
  "templates-import",
  "templates-init",
  "templates-library",
  "templates-preview",
  "terminal-notifications",
  "terminal-notifications list",
  "terminal-notifications remove",
  "terminal-notifications set",
  "terminal-notifications test",
  "time",
  "time idle",
  "time list",
  "time log",
  "time pause",
  "time report",
  "time resume",
  "time start",
  "time stop",
  "timeline",
  "tl",
  "today",
  "todos-md-import",
  "trace",
  "trust",
  "trust add",
  "trust check",
  "trust list",
  "trust remove",
  "trust status",
  "unassign",
  "unlock",
  "untag",
  "update",
  "upgrade",
  "usage",
  "usage report",
  "verify-providers",
  "verify-providers capabilities",
  "verify-providers list",
  "verify-providers remove",
  "verify-providers run",
  "verify-providers set",
  "views",
  "views delete",
  "views list",
  "views run",
  "views save",
  "watch",
  "webhooks",
  "webhooks add",
  "webhooks list",
  "webhooks match",
  "webhooks remove",
  "webhooks status",
  "webhooks test",
  "week",
  "workflow",
  "workflow migrate",
  "workflow set",
  "workflow states",
  "workflow tasks",
  "workflows",
  "workflows export",
  "workflows list",
  "workflows show",
  "yesterday",
]);
