// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.
// Regenerate: bun run scripts/generate-sdk.ts

// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Todos V1 API 0.11.96

export interface Task { "id"?: string; "title"?: string; "description"?: string; "status"?: string; "priority"?: string; "project_id"?: string | null; "assigned_to"?: string | null; "agent_id"?: string | null; "tags"?: Array<string>; "version"?: number; "created_at"?: string; "updated_at"?: string }

export interface Project { "id"?: string; "name"?: string; "path"?: string; "description"?: string | null; "task_list_id"?: string | null; "task_prefix"?: string | null; "task_counter"?: number; "created_at"?: string; "updated_at"?: string }

export interface TaskList { "id"?: string; "project_id"?: string | null; "slug"?: string; "name"?: string; "description"?: string | null; "metadata"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface TaskComment { "id": string; "task_id": string; "agent_id": string | null; "session_id": string | null; "content": string; "type": "comment" | "progress" | "note"; "progress_pct": number | null; "created_at": string }

export interface Plan { "id": string; "slug": string | null; "project_id"?: string | null; "task_list_id"?: string | null; "agent_id"?: string | null; "name": string; "description"?: string | null; "status": "active" | "completed" | "archived"; "created_at": string; "updated_at": string }

export interface Template { "id": string; "name": string; "title_pattern": string; "description"?: string | null; "priority": "low" | "medium" | "high" | "critical"; "tags": Array<string>; "variables": Array<{ "name"?: string; "required"?: boolean; "default"?: string; "description"?: string }>; "version": number; "project_id"?: string | null; "plan_id"?: string | null; "metadata": Record<string, unknown>; "created_at": string; "tasks"?: Array<TemplateTask> }

export interface TemplateTask { "id": string; "template_id": string; "position": number; "title_pattern": string; "description"?: string | null; "priority": "low" | "medium" | "high" | "critical"; "tags": Array<string>; "task_type"?: string | null; "condition"?: string | null; "include_template_id"?: string | null; "depends_on_positions": Array<number>; "metadata": Record<string, unknown>; "created_at": string }

export interface TemplateVariable { "name": string; "required": boolean; "default"?: string; "description"?: string }

export interface CreateTemplateTaskInput { "position"?: number; "title_pattern": string; "description"?: string | null; "priority"?: "low" | "medium" | "high" | "critical"; "tags"?: Array<string>; "task_type"?: string | null; "condition"?: string | null; "include_template_id"?: string | null; "depends_on"?: Array<number>; "depends_on_positions"?: Array<number>; "metadata"?: Record<string, unknown> }

export interface CreateTaskInput { "title": string; "description"?: string | null; "status"?: string; "priority"?: string; "project_id"?: string; "assigned_to"?: string; "agent_id"?: string; "tags"?: Array<string> }

export interface UpdateTaskInput { "title"?: string; "description"?: string; "status"?: string; "priority"?: string; "assigned_to"?: string; "project_id"?: string | null; "task_list_id"?: string | null; "version"?: number }

export interface CompleteTaskInput { "agent_id"?: string; "attachment_ids"?: Array<string>; "files_changed"?: Array<string>; "test_results"?: string; "commit_hash"?: string; "notes"?: string; "confidence"?: number }

export interface CreateProjectInput { "name": string; "path": string; "description"?: string; "task_list_id"?: string; "task_prefix"?: string }

export interface UpdateProjectInput { "name"?: string; "path"?: string; "description"?: string | null }

export interface RenameProjectInput { "new_slug": string; "name"?: string }

export interface ErrorResponse { "error": string; "code"?: string; "conflict"?: boolean }

export interface CreateTaskListInput { "name": string; "slug"?: string; "project_id"?: string; "description"?: string; "metadata"?: Record<string, unknown> }

export interface UpdateTaskListInput { "slug"?: string; "name"?: string; "description"?: string; "metadata"?: Record<string, unknown> }

export interface CreateTaskCommentInput { "content": string; "agent_id"?: string; "session_id"?: string; "type"?: "comment" | "progress" | "note"; "progress_pct"?: number }

export interface CreatePlanInput { "name": string; "slug"?: string; "description"?: string; "project_id"?: string; "task_list_id"?: string; "agent_id"?: string; "status"?: "active" | "completed" | "archived" }

export interface UpdatePlanInput { "name"?: string; "slug"?: string; "description"?: string; "task_list_id"?: string; "agent_id"?: string; "status"?: "active" | "completed" | "archived" }

export interface CreateTemplateInput { "name": string; "title_pattern": string; "description"?: string | null; "priority"?: "low" | "medium" | "high" | "critical"; "tags"?: Array<string>; "variables"?: Array<TemplateVariable>; "project_id"?: string | null; "plan_id"?: string | null; "metadata"?: Record<string, unknown>; "tasks"?: Array<CreateTemplateTaskInput> }

export interface UpdateTemplateInput { "name"?: string; "title_pattern"?: string; "description"?: string | null; "priority"?: "low" | "medium" | "high" | "critical"; "tags"?: Array<string>; "variables"?: Array<Record<string, unknown>>; "project_id"?: string | null; "plan_id"?: string | null; "metadata"?: Record<string, unknown> }

export interface TodosV1ClientOptions {
  /** Base URL, e.g. process.env.APP_API_URL. */
  baseUrl: string;
  /** API key, e.g. process.env.APP_API_KEY. Sent as the 'x-api-key' header. */
  apiKey?: string;
  /** Custom fetch (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  constructor(readonly status: number, message: string, readonly body: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export class TodosV1Client {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly fetchImpl: typeof fetch;
  private readonly baseHeaders: Record<string, string>;

  constructor(options: TodosV1ClientOptions) {
    if (!options.baseUrl) throw new Error("TodosV1Client requires a baseUrl.");
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.baseHeaders = options.headers ?? {};
  }

  private async request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (opts.query) {
      for (const [key, value] of Object.entries(opts.query)) {
        if (value !== undefined && value !== null) url.searchParams.set(key, String(value));
      }
    }
    const headers: Record<string, string> = { Accept: "application/json", ...this.baseHeaders, ...(opts.init?.headers as Record<string, string> | undefined) };
    if (this.apiKey) headers["x-api-key"] = this.apiKey;
    let payload: BodyInit | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      payload = JSON.stringify(opts.body);
    }
    const response = await this.fetchImpl(url.toString(), { ...opts.init, method, headers, body: payload });
    const text = await response.text();
    const data = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : undefined;
    if (!response.ok) {
      throw new ApiError(response.status, `${method} ${path} failed: ${response.status}`, data);
    }
    return data as T;
  }

    /** Bulk-ingest a full or partial snapshot (idempotent upsert by id) */
    async importSnapshot(body: { "exportedAt"?: string; "source"?: string; "tasks"?: Array<Task>; "projects"?: Array<Project>; "projectMachinePaths"?: Array<Record<string, unknown>>; "plans"?: Array<Record<string, unknown>>; "agents"?: Array<Record<string, unknown>>; "taskLists"?: Array<Record<string, unknown>>; "templates"?: Array<Record<string, unknown>>; "templateTasks"?: Array<TemplateTask>; "auditHistory"?: Array<Record<string, unknown>>; "tombstones"?: Array<Record<string, unknown>> }, init?: RequestInit): Promise<{ "received"?: number; "result"?: { "inserted"?: number; "updated"?: number; "deleted"?: number; "skipped"?: number; "errors"?: Array<string> } }> {
      return this.request("POST", `/v1/import`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List plans */
    async listPlans(query?: { "project_id"?: string }, init?: RequestInit): Promise<{ "plans"?: Array<Plan>; "count"?: number }> {
      return this.request("GET", `/v1/plans`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a plan */
    async createPlan(body: CreatePlanInput, init?: RequestInit): Promise<{ "plan"?: Plan }> {
      return this.request("POST", `/v1/plans`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a plan by id */
    async getPlan(id: string, init?: RequestInit): Promise<{ "plan"?: Plan }> {
      return this.request("GET", `/v1/plans/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a plan and detach its tasks */
    async deletePlan(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/plans/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a plan */
    async updatePlan(id: string, body: UpdatePlanInput, init?: RequestInit): Promise<{ "plan"?: Plan }> {
      return this.request("PATCH", `/v1/plans/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List projects */
    async listProjects(init?: RequestInit): Promise<{ "projects"?: Array<Project>; "count"?: number }> {
      return this.request("GET", `/v1/projects`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Create a project */
    async createProject(body: CreateProjectInput, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("POST", `/v1/projects`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a project by id */
    async getProject(id: string, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("GET", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a project */
    async deleteProject(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a project */
    async updateProject(id: string, body: UpdateProjectInput, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("PATCH", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Atomically rename a project and its canonical task list */
    async renameProject(id: string, body: RenameProjectInput, init?: RequestInit): Promise<{ "project"?: Project; "task_lists_updated"?: number }> {
      return this.request("POST", `/v1/projects/${encodeURIComponent(String(id))}/rename`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Aggregate counts */
    async getStats(init?: RequestInit): Promise<{ "tasks"?: number; "projects"?: number }> {
      return this.request("GET", `/v1/stats`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List task lists */
    async listTaskLists(query?: { "project_id"?: string }, init?: RequestInit): Promise<{ "task_lists"?: Array<TaskList>; "count"?: number }> {
      return this.request("GET", `/v1/task-lists`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task list */
    async createTaskList(body: CreateTaskListInput, init?: RequestInit): Promise<{ "task_list"?: TaskList }> {
      return this.request("POST", `/v1/task-lists`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a task list by id */
    async getTaskList(id: string, init?: RequestInit): Promise<{ "task_list"?: TaskList }> {
      return this.request("GET", `/v1/task-lists/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a task list */
    async deleteTaskList(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/task-lists/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a task list */
    async updateTaskList(id: string, body: UpdateTaskListInput, init?: RequestInit): Promise<{ "task_list"?: TaskList }> {
      return this.request("PATCH", `/v1/task-lists/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List tasks */
    async listTasks(query?: { "status"?: string; "priority"?: string; "project_id"?: string; "parent_id"?: string | null; "include_subtasks"?: boolean; "plan_id"?: string; "task_list_id"?: string; "assigned_to"?: string; "agent_id"?: string; "limit"?: number; "offset"?: number }, init?: RequestInit): Promise<{ "tasks": Array<Task>; "count": number; "total": number }> {
      return this.request("GET", `/v1/tasks`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task */
    async createTask(body: CreateTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a task by id */
    async getTask(id: string, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("GET", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a task */
    async deleteTask(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a task */
    async updateTask(id: string, body: UpdateTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("PATCH", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List a bounded page of task comments */
    async listTaskComments(id: string, query?: { "limit": number; "cursor"?: string }, init?: RequestInit): Promise<{ "comments": Array<TaskComment>; "count": number; "has_more": boolean; "next_cursor": string | null }> {
      return this.request("GET", `/v1/tasks/${encodeURIComponent(String(id))}/comments`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task comment */
    async createTaskComment(id: string, body: CreateTaskCommentInput, init?: RequestInit): Promise<{ "comment": TaskComment }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/comments`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Complete a task */
    async completeTask(id: string, body?: CompleteTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/complete`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Start a task */
    async startTask(id: string, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/start`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List reusable task templates */
    async listTemplates(query?: { "project_id"?: string }, init?: RequestInit): Promise<{ "templates"?: Array<Template>; "count"?: number }> {
      return this.request("GET", `/v1/templates`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a reusable task template */
    async createTemplate(body: CreateTemplateInput, init?: RequestInit): Promise<{ "template"?: Template }> {
      return this.request("POST", `/v1/templates`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get one reusable task template with its checklist steps */
    async getTemplate(id: string, init?: RequestInit): Promise<{ "template"?: Template }> {
      return this.request("GET", `/v1/templates/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a reusable task template and its checklist steps */
    async deleteTemplate(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/templates/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update reusable template metadata and defaults */
    async updateTemplate(id: string, body: UpdateTemplateInput, init?: RequestInit): Promise<{ "template"?: Template }> {
      return this.request("PATCH", `/v1/templates/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }
}
