// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.
// Regenerate: bun run scripts/generate-sdk.ts

// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Todos V1 API 0.11.92

export interface Task { "id"?: string; "title"?: string; "description"?: string; "status"?: "pending" | "in_progress" | "completed" | "failed" | "cancelled"; "priority"?: "low" | "medium" | "high" | "critical"; "project_id"?: string | null; "assigned_to"?: string | null; "agent_id"?: string | null; "tags"?: Array<string>; "version"?: number; "created_at"?: string; "updated_at"?: string }

export interface Project { "id"?: string; "name"?: string; "path"?: string; "description"?: string | null; "task_list_id"?: string | null; "task_prefix"?: string | null; "task_counter"?: number; "created_at"?: string; "updated_at"?: string }

export interface TaskList { "id"?: string; "project_id"?: string | null; "slug"?: string; "name"?: string; "description"?: string | null; "metadata"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface TaskComment { "id": string; "task_id": string; "agent_id": string | null; "session_id": string | null; "content": string; "type": "comment" | "progress" | "note"; "progress_pct": number | null; "created_at": string }

export interface Plan { "id": string; "slug": string | null; "project_id"?: string | null; "task_list_id"?: string | null; "agent_id"?: string | null; "name": string; "description"?: string | null; "status": "active" | "completed" | "archived"; "created_at": string; "updated_at": string }

export interface Incident { "id": string; "title": string; "severity": "info" | "low" | "medium" | "high" | "critical"; "status": "open" | "investigating" | "contained" | "monitoring" | "resolved" | "superseded"; "owner": string; "affected_scopes": Array<string>; "blocked_scopes": Array<string>; "containment": string | null; "next_action": string | null; "deadline": string | null; "closure_evidence": Array<string>; "supersedes_id": string | null; "superseded_by_id": string | null; "resolved_at": string | null; "version": number; "created_at": string; "updated_at": string }

export interface IncidentTransition { "id": string; "authority_id": string; "incident_id": string; "incident_version": number; "idempotency_key": string; "request_fingerprint": string; "action": "created" | "updated" | "resolved" | "superseded"; "actor_id": string; "effective_actor_id": string; "actor_key_id": string | null; "actor_act_as": boolean; "reason": string; "before": { "id": string; "title": string; "severity": "info" | "low" | "medium" | "high" | "critical"; "status": "open" | "investigating" | "contained" | "monitoring" | "resolved" | "superseded"; "owner": string; "affected_scopes": Array<string>; "blocked_scopes": Array<string>; "containment": string | null; "next_action": string | null; "deadline": string | null; "closure_evidence": Array<string>; "supersedes_id": string | null; "superseded_by_id": string | null; "resolved_at": string | null; "version": number; "created_at": string; "updated_at": string } | null; "after": { "id": string; "title": string; "severity": "info" | "low" | "medium" | "high" | "critical"; "status": "open" | "investigating" | "contained" | "monitoring" | "resolved" | "superseded"; "owner": string; "affected_scopes": Array<string>; "blocked_scopes": Array<string>; "containment": string | null; "next_action": string | null; "deadline": string | null; "closure_evidence": Array<string>; "supersedes_id": string | null; "superseded_by_id": string | null; "resolved_at": string | null; "version": number; "created_at": string; "updated_at": string }; "created_at": string }

export interface IncidentProjectionEvent { "schema_version": 1; "source": "todos"; "event_id": string; "projection_key": string; "authority_id": string; "incident_id": string; "transition_id": string; "incident_version": number; "occurred_at": string; "incident": { "id": string; "title": string; "severity": "info" | "low" | "medium" | "high" | "critical"; "status": "open" | "investigating" | "contained" | "monitoring" | "resolved" | "superseded"; "owner": string; "affected_scopes": Array<string>; "blocked_scopes": Array<string>; "containment": string | null; "next_action": string | null; "deadline": string | null; "closure_evidence": Array<string>; "supersedes_id": string | null; "superseded_by_id": string | null; "resolved_at": string | null; "version": number; "created_at": string; "updated_at": string } }

export interface IncidentOutboxRecord { "event_id": string; "projection_key": string; "incident_id": string; "incident_version": number; "depends_on_event_id": string | null; "payload": { "schema_version": 1; "source": "todos"; "event_id": string; "projection_key": string; "authority_id": string; "incident_id": string; "transition_id": string; "incident_version": number; "occurred_at": string; "incident": { "id": string; "title": string; "severity": "info" | "low" | "medium" | "high" | "critical"; "status": "open" | "investigating" | "contained" | "monitoring" | "resolved" | "superseded"; "owner": string; "affected_scopes": Array<string>; "blocked_scopes": Array<string>; "containment": string | null; "next_action": string | null; "deadline": string | null; "closure_evidence": Array<string>; "supersedes_id": string | null; "superseded_by_id": string | null; "resolved_at": string | null; "version": number; "created_at": string; "updated_at": string } }; "status": "pending" | "leased" | "acked" | "dead"; "attempts": number; "next_attempt_at": string; "lease_token": string | null; "leased_by": string | null; "lease_expires_at": string | null; "delivery_id": string | null; "acked_at": string | null; "last_error": string | null; "failure_code": string | null; "failure_fingerprint": string | null; "consecutive_failures": number; "created_at": string; "updated_at": string }

export interface IncidentMutationResult { "incident": Incident; "transitions": Array<IncidentTransition>; "events": Array<IncidentProjectionEvent>; "replayed": boolean }

export interface CreateIncidentInput { "id": string; "idempotency_key": string; "title": string; "severity": "info" | "low" | "medium" | "high" | "critical"; "status"?: "open" | "investigating" | "contained" | "monitoring"; "owner": string; "affected_scopes": Array<string>; "blocked_scopes"?: Array<string>; "containment"?: string | null; "next_action": string; "deadline"?: string | null; "closure_evidence"?: Array<string>; "supersedes_id"?: string | null; "supersedes_expected_version"?: number | null }

export interface TransitionIncidentInput { "expected_version": number; "idempotency_key": string; "reason": string; "title"?: string; "severity"?: "info" | "low" | "medium" | "high" | "critical"; "status"?: "open" | "investigating" | "contained" | "monitoring" | "resolved"; "owner"?: string; "affected_scopes"?: Array<string>; "blocked_scopes"?: Array<string>; "containment"?: string | null; "next_action"?: string | null; "deadline"?: string | null; "closure_evidence"?: Array<string> }

export interface CreateTaskInput { "title": string; "description"?: string; "status"?: "pending" | "in_progress" | "completed" | "failed" | "cancelled"; "priority"?: "low" | "medium" | "high" | "critical"; "project_id"?: string; "assigned_to"?: string; "agent_id"?: string; "assigned_by"?: string; "tags"?: Array<string> }

export interface UpdateTaskInput { "title"?: string; "description"?: string; "status"?: "pending" | "in_progress" | "completed" | "failed" | "cancelled"; "priority"?: "low" | "medium" | "high" | "critical"; "project_id"?: string | null; "assigned_to"?: string | null; "working_dir"?: string | null; "plan_id"?: string | null; "task_list_id"?: string | null; "cycle_id"?: string | null; "tags"?: Array<string>; "metadata"?: Record<string, unknown>; "due_at"?: string | null; "estimated_minutes"?: number; "sla_minutes"?: number | null; "actual_minutes"?: number; "completed_at"?: string | null; "confidence"?: number | null; "retry_count"?: number; "max_retries"?: number; "retry_after"?: string | null; "requires_approval"?: boolean; "approved_by"?: string; "recurrence_rule"?: string | null; "version"?: number; "task_type"?: string | null }

export interface CompleteTaskInput { "agent_id"?: string; "attachment_ids"?: Array<string>; "files_changed"?: Array<string>; "test_results"?: string; "commit_hash"?: string; "notes"?: string; "confidence"?: number }

export interface FailTaskInput { "agent_id"?: string; "reason"?: string; "retry"?: boolean; "retry_after"?: string; "error_code"?: string }

export interface CreateProjectInput { "name": string; "path": string; "description"?: string; "task_list_id"?: string; "task_prefix"?: string }

export interface UpdateProjectInput { "name"?: string; "path"?: string; "description"?: string | null }

export interface RenameProjectInput { "new_slug": string; "name"?: string }

export interface ErrorResponse { "error": string; "code"?: string; "conflict"?: boolean }

export interface CreateTaskListInput { "name": string; "slug"?: string; "project_id"?: string; "description"?: string; "metadata"?: Record<string, unknown> }

export interface UpdateTaskListInput { "slug"?: string; "name"?: string; "description"?: string; "metadata"?: Record<string, unknown> }

export interface CreateTaskCommentInput { "content": string; "agent_id"?: string; "session_id"?: string; "type"?: "comment" | "progress" | "note"; "progress_pct"?: number }

export interface CreatePlanInput { "name": string; "slug"?: string; "description"?: string; "project_id"?: string; "task_list_id"?: string; "agent_id"?: string; "status"?: "active" | "completed" | "archived" }

export interface UpdatePlanInput { "name"?: string; "slug"?: string; "description"?: string; "task_list_id"?: string; "agent_id"?: string; "status"?: "active" | "completed" | "archived" }

export interface TodosV1ClientOptions {
  /** Base URL, e.g. process.env.APP_API_URL. */
  baseUrl: string;
  /** API key, e.g. process.env.APP_API_KEY. Sent as the 'x-api-key' header. */
  apiKey?: string;
  /** Custom fetch (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  constructor(readonly status: number, message: string, readonly body: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export class TodosV1Client {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly fetchImpl: typeof fetch;
  private readonly baseHeaders: Record<string, string>;

  constructor(options: TodosV1ClientOptions) {
    if (!options.baseUrl) throw new Error("TodosV1Client requires a baseUrl.");
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.baseHeaders = options.headers ?? {};
  }

  private async request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (opts.query) {
      for (const [key, value] of Object.entries(opts.query)) {
        if (value !== undefined && value !== null) url.searchParams.set(key, String(value));
      }
    }
    const headers: Record<string, string> = { Accept: "application/json", ...this.baseHeaders, ...(opts.init?.headers as Record<string, string> | undefined) };
    if (this.apiKey) headers["x-api-key"] = this.apiKey;
    let payload: BodyInit | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      payload = JSON.stringify(opts.body);
    }
    const response = await this.fetchImpl(url.toString(), { ...opts.init, method, headers, body: payload });
    const text = await response.text();
    const data = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : undefined;
    if (!response.ok) {
      throw new ApiError(response.status, `${method} ${path} failed: ${response.status}`, data);
    }
    return data as T;
  }

    /** Bulk-ingest a full or partial snapshot (idempotent upsert by id) */
    async importSnapshot(body: { "exportedAt"?: string; "source"?: string; "tasks"?: Array<Task>; "projects"?: Array<Project>; "projectMachinePaths"?: Array<Record<string, unknown>>; "plans"?: Array<Record<string, unknown>>; "agents"?: Array<Record<string, unknown>>; "taskLists"?: Array<Record<string, unknown>>; "templates"?: Array<Record<string, unknown>>; "auditHistory"?: Array<Record<string, unknown>>; "tombstones"?: Array<Record<string, unknown>> }, init?: RequestInit): Promise<{ "received"?: number; "result"?: { "inserted"?: number; "updated"?: number; "deleted"?: number; "skipped"?: number; "errors"?: Array<string> } }> {
      return this.request("POST", `/v1/import`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List canonical incidents */
    async listIncidents(query?: { "status"?: "open" | "investigating" | "contained" | "monitoring" | "resolved" | "superseded"; "severity"?: "info" | "low" | "medium" | "high" | "critical"; "owner"?: string; "scope"?: string; "active"?: boolean; "limit"?: number; "before_updated_at"?: string; "before_id"?: string }, init?: RequestInit): Promise<{ "incidents": Array<Incident>; "count": number }> {
      return this.request("GET", `/v1/incidents`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create or atomically supersede a canonical incident */
    async createIncident(body: CreateIncidentInput, init?: RequestInit): Promise<{ "result": IncidentMutationResult }> {
      return this.request("POST", `/v1/incidents`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List active canonical blockers */
    async listIncidentBlockers(query?: { "severity"?: "info" | "low" | "medium" | "high" | "critical"; "owner"?: string; "scope"?: string; "limit"?: number; "before_updated_at"?: string; "before_id"?: string }, init?: RequestInit): Promise<{ "incidents": Array<Incident>; "count": number; "active_statuses": Array<"open" | "investigating" | "contained" | "monitoring"> }> {
      return this.request("GET", `/v1/incidents/blockers`, {
        body: undefined,
        query,
        init,
      });
    }

    /** List dead incident projection events for operator recovery */
    async listDeadIncidentOutbox(query?: { "limit"?: number; "before_created_at"?: string; "before_event_id"?: string }, init?: RequestInit): Promise<{ "outbox": Array<IncidentOutboxRecord>; "count": number }> {
      return this.request("GET", `/v1/incidents/outbox`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Lease causally ready incident projections */
    async claimIncidentOutbox(body?: { "limit"?: number; "lease_seconds"?: number }, init?: RequestInit): Promise<{ "outbox": Array<IncidentOutboxRecord>; "count": number }> {
      return this.request("POST", `/v1/incidents/outbox/claim`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get authority-scoped incident projection outbox counts */
    async getIncidentOutboxStatus(init?: RequestInit): Promise<{ "status": { "pending": number; "leased": number; "acked": number; "dead": number; "total": number } }> {
      return this.request("GET", `/v1/incidents/outbox/status`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Get one exact dead incident projection event */
    async getDeadIncidentOutbox(eventId: string, init?: RequestInit): Promise<{ "outbox": IncidentOutboxRecord }> {
      return this.request("GET", `/v1/incidents/outbox/${encodeURIComponent(String(eventId))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Acknowledge an exact projection lease */
    async ackIncidentOutbox(eventId: string, body: { "lease_token": string; "delivery_id": string }, init?: RequestInit): Promise<{ "outbox": IncidentOutboxRecord }> {
      return this.request("POST", `/v1/incidents/outbox/${encodeURIComponent(String(eventId))}/ack`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Fail an exact projection lease with bounded backoff */
    async failIncidentOutbox(eventId: string, body: { "lease_token": string; "failure_code": string; "failure": string }, init?: RequestInit): Promise<{ "outbox": IncidentOutboxRecord }> {
      return this.request("POST", `/v1/incidents/outbox/${encodeURIComponent(String(eventId))}/fail`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Audit and requeue one exact dead projection */
    async requeueIncidentOutbox(eventId: string, body: { "expected_attempts": number; "idempotency_key": string; "reason": string }, init?: RequestInit): Promise<{ "outbox": IncidentOutboxRecord }> {
      return this.request("POST", `/v1/incidents/outbox/${encodeURIComponent(String(eventId))}/requeue`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a canonical incident */
    async getIncident(id: string, init?: RequestInit): Promise<{ "incident": Incident }> {
      return this.request("GET", `/v1/incidents/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List immutable incident transitions */
    async listIncidentTransitions(id: string, init?: RequestInit): Promise<{ "transitions": Array<IncidentTransition>; "count": number }> {
      return this.request("GET", `/v1/incidents/${encodeURIComponent(String(id))}/transitions`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** CAS-transition a canonical incident */
    async transitionIncident(id: string, body: TransitionIncidentInput, init?: RequestInit): Promise<{ "result": IncidentMutationResult }> {
      return this.request("POST", `/v1/incidents/${encodeURIComponent(String(id))}/transitions`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List plans */
    async listPlans(query?: { "project_id"?: string }, init?: RequestInit): Promise<{ "plans"?: Array<Plan>; "count"?: number }> {
      return this.request("GET", `/v1/plans`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a plan */
    async createPlan(body: CreatePlanInput, init?: RequestInit): Promise<{ "plan"?: Plan }> {
      return this.request("POST", `/v1/plans`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a plan by id */
    async getPlan(id: string, init?: RequestInit): Promise<{ "plan"?: Plan }> {
      return this.request("GET", `/v1/plans/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a plan and detach its tasks */
    async deletePlan(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/plans/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a plan */
    async updatePlan(id: string, body: UpdatePlanInput, init?: RequestInit): Promise<{ "plan"?: Plan }> {
      return this.request("PATCH", `/v1/plans/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List projects */
    async listProjects(init?: RequestInit): Promise<{ "projects"?: Array<Project>; "count"?: number }> {
      return this.request("GET", `/v1/projects`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Create a project */
    async createProject(body: CreateProjectInput, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("POST", `/v1/projects`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a project by id */
    async getProject(id: string, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("GET", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a project */
    async deleteProject(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a project */
    async updateProject(id: string, body: UpdateProjectInput, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("PATCH", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Atomically rename a project and its canonical task list */
    async renameProject(id: string, body: RenameProjectInput, init?: RequestInit): Promise<{ "project"?: Project; "task_lists_updated"?: number }> {
      return this.request("POST", `/v1/projects/${encodeURIComponent(String(id))}/rename`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Aggregate counts */
    async getStats(init?: RequestInit): Promise<{ "tasks"?: number; "projects"?: number }> {
      return this.request("GET", `/v1/stats`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List task lists */
    async listTaskLists(query?: { "project_id"?: string }, init?: RequestInit): Promise<{ "task_lists"?: Array<TaskList>; "count"?: number }> {
      return this.request("GET", `/v1/task-lists`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task list */
    async createTaskList(body: CreateTaskListInput, init?: RequestInit): Promise<{ "task_list"?: TaskList }> {
      return this.request("POST", `/v1/task-lists`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a task list by id */
    async getTaskList(id: string, init?: RequestInit): Promise<{ "task_list"?: TaskList }> {
      return this.request("GET", `/v1/task-lists/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a task list */
    async deleteTaskList(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/task-lists/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a task list */
    async updateTaskList(id: string, body: UpdateTaskListInput, init?: RequestInit): Promise<{ "task_list"?: TaskList }> {
      return this.request("PATCH", `/v1/task-lists/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List tasks */
    async listTasks(query?: { "status"?: string; "priority"?: string; "project_id"?: string; "parent_id"?: string | null; "include_subtasks"?: boolean; "plan_id"?: string; "task_list_id"?: string; "assigned_to"?: string; "agent_id"?: string; "limit"?: number; "offset"?: number }, init?: RequestInit): Promise<{ "tasks": Array<Task>; "count": number; "total": number }> {
      return this.request("GET", `/v1/tasks`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task */
    async createTask(body: CreateTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a task by id */
    async getTask(id: string, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("GET", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a task */
    async deleteTask(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a task */
    async updateTask(id: string, body: UpdateTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("PATCH", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List a bounded page of task comments */
    async listTaskComments(id: string, query?: { "limit": number; "cursor"?: string }, init?: RequestInit): Promise<{ "comments": Array<TaskComment>; "count": number; "has_more": boolean; "next_cursor": string | null }> {
      return this.request("GET", `/v1/tasks/${encodeURIComponent(String(id))}/comments`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task comment */
    async createTaskComment(id: string, body: CreateTaskCommentInput, init?: RequestInit): Promise<{ "comment": TaskComment }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/comments`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Complete a task */
    async completeTask(id: string, body?: CompleteTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/complete`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Mark a task failed and optionally create a retry copy */
    async failTask(id: string, body?: FailTaskInput, init?: RequestInit): Promise<{ "result"?: { "task"?: Task; "retryTask"?: Task } }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/fail`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Start a task */
    async startTask(id: string, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/start`, {
        body: undefined,
        query: undefined,
        init,
      });
    }
}
