// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.
// Regenerate: bun run scripts/generate-sdk.ts

// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Todos V1 API 0.11.75

export interface Task { "id"?: string; "title"?: string; "description"?: string; "status"?: string; "priority"?: string; "project_id"?: string | null; "assigned_to"?: string | null; "agent_id"?: string | null; "tags"?: Array<string>; "version"?: number; "created_at"?: string; "updated_at"?: string }

export interface Project { "id"?: string; "name"?: string; "path"?: string; "description"?: string | null; "created_at"?: string; "updated_at"?: string }

export interface CreateTaskInput { "title": string; "description"?: string; "status"?: string; "priority"?: string; "project_id"?: string; "assigned_to"?: string; "agent_id"?: string; "tags"?: Array<string> }

export interface UpdateTaskInput { "title"?: string; "description"?: string; "status"?: string; "priority"?: string; "assigned_to"?: string; "version"?: number }

export interface CreateProjectInput { "name": string; "path": string; "description"?: string; "task_prefix"?: string }

export interface TodosV1ClientOptions {
  /** Base URL, e.g. process.env.APP_API_URL. */
  baseUrl: string;
  /** API key, e.g. process.env.APP_API_KEY. Sent as the 'x-api-key' header. */
  apiKey?: string;
  /** Custom fetch (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  constructor(readonly status: number, message: string, readonly body: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export class TodosV1Client {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly fetchImpl: typeof fetch;
  private readonly baseHeaders: Record<string, string>;

  constructor(options: TodosV1ClientOptions) {
    if (!options.baseUrl) throw new Error("TodosV1Client requires a baseUrl.");
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.baseHeaders = options.headers ?? {};
  }

  private async request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (opts.query) {
      for (const [key, value] of Object.entries(opts.query)) {
        if (value !== undefined && value !== null) url.searchParams.set(key, String(value));
      }
    }
    const headers: Record<string, string> = { Accept: "application/json", ...this.baseHeaders, ...(opts.init?.headers as Record<string, string> | undefined) };
    if (this.apiKey) headers["x-api-key"] = this.apiKey;
    let payload: BodyInit | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      payload = JSON.stringify(opts.body);
    }
    const response = await this.fetchImpl(url.toString(), { ...opts.init, method, headers, body: payload });
    const text = await response.text();
    const data = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : undefined;
    if (!response.ok) {
      throw new ApiError(response.status, `${method} ${path} failed: ${response.status}`, data);
    }
    return data as T;
  }

    /** List projects */
    async listProjects(init?: RequestInit): Promise<{ "projects"?: Array<Project>; "count"?: number }> {
      return this.request("GET", `/v1/projects`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Create a project */
    async createProject(body: CreateProjectInput, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("POST", `/v1/projects`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a project by id */
    async getProject(id: string, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("GET", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Aggregate counts */
    async getStats(init?: RequestInit): Promise<{ "tasks"?: number; "projects"?: number }> {
      return this.request("GET", `/v1/stats`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List tasks */
    async listTasks(query?: { "status"?: string; "project_id"?: string; "assigned_to"?: string; "agent_id"?: string; "limit"?: number }, init?: RequestInit): Promise<{ "tasks"?: Array<Task>; "count"?: number }> {
      return this.request("GET", `/v1/tasks`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task */
    async createTask(body: CreateTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a task by id */
    async getTask(id: string, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("GET", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a task */
    async deleteTask(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a task */
    async updateTask(id: string, body: UpdateTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("PATCH", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Complete a task */
    async completeTask(id: string, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/complete`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Start a task */
    async startTask(id: string, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/start`, {
        body: undefined,
        query: undefined,
        init,
      });
    }
}
