#!/usr/bin/env bun
/**
 * Generate the typed `/v1` SDK client from the serve OpenAPI document.
 *
 * Source of truth: src/server/openapi.ts (also served at GET /openapi.json).
 * Output: src/sdk/v1.generated.ts — a dependency-free typed fetch client.
 *
 * Usage: bun run scripts/generate-sdk.ts
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateSdkFromOpenApi } from "@hasna/contracts/sdk";
import { buildV1OpenApiDocument } from "../src/server/openapi.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spec = buildV1OpenApiDocument();
const { code, operations, warnings } = generateSdkFromOpenApi(spec as never, {
  className: "TodosV1Client",
  apiKeyHeader: "x-api-key",
});

const header =
  "// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.\n" +
  "// Regenerate: bun run scripts/generate-sdk.ts\n\n";
const outPath = join(root, "src/sdk/v1.generated.ts");
writeFileSync(outPath, header + code);

console.log(`Wrote ${outPath}`);
console.log(`Operations: ${operations.map((o) => o.functionName).join(", ")}`);
if (warnings.length) console.log(`Warnings:\n  ${warnings.join("\n  ")}`);
